openapi: '3.0.2'
info:
  description: '## A basic nodejs express webapp, packed as docker container run with docker compose' 
  version: 1.0.0
  title: 20-Docker-Compose
servers:
  - url: http://localhost:10081
paths: 
  /:
    get:
      summary: Response this request with Hello World
      description: ""
      responses:
        "200":
          description: Success
          content:
            text/html: 
              schema: 
                type: string
                example: "Hello World"